# Server
server:
  port: 8080
  servlet:
    contextPath: "/e-commerce"

# Relacional Database
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/my-ecommerce?serverTimezone=UTC"
    username: "root"
    password: "250128518"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    initialization-mode: "always"
  jpa:
    open-in-view: true
    properties: #https://github.com/spring-projects/spring-data-jpa/issues/2717
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
      jakarta:
        persistence:
          sharedCache:
            #ALL | NONE | ENABLE_SELECTIVE | DISABLE_SELECTIVE | UNSPECIFIED
            mode: UNSPECIFIED
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
  #jackson:
    #serialization:
      #write-datas-as-timestamps: false
    #default-property-inclusion: non_null
  #main:
    #allow-bean-definition-overriding: true

# Cached Database
  redis:
    host: "localhost"
    port: 6379
    password: ""
