# Server
server:
  port: 8080
  servlet:
    contextPath: "/e-commerce"

# Relacional Database
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/my-ecommerce?serverTimezone=UTC"
    username: "root"
    password: "admin"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    initialization-mode: "always"
  jpa:
    open-in-view: true
    properties: #https://github.com/spring-projects/spring-data-jpa/issues/2717
      jakarta:
        persistence:
          sharedCache:
            #ALL | NONE | ENABLE_SELECTIVE | DISABLE_SELECTIVE | UNSPECIFIED
            mode: UNSPECIFIED

# Cached Database
redis:
  host: "localhost"
  port: 6379
  password: "****"

hibernate:
  dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: update
  id.new_generator_mappings: true
